spring:
  application:
    name: graalvmnativeimagejdbcdriver

  # Datasource Configuration
  datasource:
    url: jdbc:oracle:thin:@${TNS_NAME}?TNS_ADMIN=${WALLET_DIR}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: ConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30